### ISSUE TITLE
caught SyntaxError: The requested module '/node_modules/.vite/deps/react-icons_ri.js?v=76252418' does not provide an export named 'RiCloseRin' (at Navbar.jsx:17:23)

### ISSUE THREAD

**Issue by Nicitaa** [adrianhajdin/project_modern_ui_ux_gpt3#27]
caught SyntaxError: The requested module '/node_modules/.vite/deps/react-icons_ri.js?v=76252418' does not provide an export named 'RiCloseRin' (at Navbar.jsx:17:23)

**Comment by Nicitaa** [comment]
1)Rename index.js to main.jsx
2)paste this to main.jsx

import React from 'react';
import ReactDOM from 'react-dom/client'

import App from './App'
import './index.css'

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
    <App />
);

3)Change import to this in 'components/navbar/Navbar.jsx'

import {RiMenu3Line,RiCloseLine} from 'react-icons/ri'
